// Server-side mirror of client/src/assets/data/tracks.ts.
// Only the fields /api/music/signed-url needs: id, category, isPro, path.
// Title is intentionally omitted — the server never displays track names,
// it only verifies access and signs a URL.
//
// IMPORTANT: this file must stay in sync with the client catalog manually.
// If you add/remove/re-tier a track on the client, mirror the change here
// or the signed-url route will 404 or mis-gate it. Consider generating both
// files from one shared JSON/CSV at build time to remove this duplication
// risk entirely — that's the real fix; this is the stopgap.
export const TRACKS = [
  // ─── FOCUS — Free ──────────────────────────────────────────────────────
  { id: 'focus-001', category: 'focus', isPro: false, path: 'focus/morning-pages.mp3' },
  { id: 'focus-002', category: 'focus', isPro: false, path: 'focus/first-coffee-thoughts.mp3' },
  { id: 'focus-003', category: 'focus', isPro: false, path: 'focus/graphite-mornings.mp3' },
  { id: 'focus-004', category: 'focus', isPro: false, path: 'focus/2-am-debug-loop.mp3' },
  { id: 'focus-028', category: 'focus', isPro: false, path: 'focus/terminal-rain.mp3' },
  { id: 'focus-036', category: 'focus', isPro: false, path: 'focus/sunset-offbeat.mp3' },
  { id: 'focus-045', category: 'focus', isPro: false, path: 'focus/midnight-amber-room.mp3' },

  // ─── FOCUS — Pro ───────────────────────────────────────────────────────
  { id: 'focus-005', category: 'focus', isPro: true, path: 'focus/brushstrokes-and-rain.mp3' },
  { id: 'focus-006', category: 'focus', isPro: true, path: 'focus/butter-and-windowlight.mp3' },
  { id: 'focus-007', category: 'focus', isPro: true, path: 'focus/chapter-by-lamplight.mp3' },
  { id: 'focus-008', category: 'focus', isPro: true, path: 'focus/coffee-ring-notebook.mp3' },
  { id: 'focus-009', category: 'focus', isPro: true, path: 'focus/continue-screen-dreams.mp3' },
  { id: 'focus-010', category: 'focus', isPro: true, path: 'focus/cursor-after-midnight.mp3' },
  { id: 'focus-011', category: 'focus', isPro: true, path: 'focus/dog-eared-pages.mp3' },
  { id: 'focus-012', category: 'focus', isPro: true, path: 'focus/dust-in-the-curtains.mp3' },
  { id: 'focus-013', category: 'focus', isPro: true, path: 'focus/exhale-the-morning.mp3' },
  { id: 'focus-014', category: 'focus', isPro: true, path: 'focus/faded-corners-of-the-page.mp3' },
  { id: 'focus-015', category: 'focus', isPro: true, path: 'focus/graphite-in-the-quiet.mp3' },
  { id: 'focus-016', category: 'focus', isPro: true, path: 'focus/hour-between-clicks.mp3' },
  { id: 'focus-017', category: 'focus', isPro: true, path: 'focus/kettle-before-work.mp3' },
  { id: 'focus-018', category: 'focus', isPro: true, path: 'focus/margin-notes-at-dusk.mp3' },
  { id: 'focus-019', category: 'focus', isPro: true, path: 'focus/mat-and-morning-light.mp3' },
  { id: 'focus-020', category: 'focus', isPro: true, path: 'focus/morning-in-the-hiss.mp3' },
  { id: 'focus-021', category: 'focus', isPro: true, path: 'focus/pancakes-in-the-sun.mp3' },
  { id: 'focus-022', category: 'focus', isPro: true, path: 'focus/penciled-sunbeams.mp3' },
  { id: 'focus-023', category: 'focus', isPro: true, path: 'focus/pixel-quest-save-point.mp3' },
  { id: 'focus-024', category: 'focus', isPro: true, path: 'focus/quiet-lungs-quiet-light.mp3' },
  { id: 'focus-025', category: 'focus', isPro: true, path: 'focus/stacks-of-quiet-hours.mp3' },
  { id: 'focus-026', category: 'focus', isPro: true, path: 'focus/sunday-light-through-lace.mp3' },
  { id: 'focus-027', category: 'focus', isPro: true, path: 'focus/sunrise-stretch-flow.mp3' },
  { id: 'focus-029', category: 'focus', isPro: true, path: 'focus/watercolors-by-the-window.mp3' },
  { id: 'focus-030', category: 'focus', isPro: true, path: 'focus/dusk-between-stoops.mp3' },
  { id: 'focus-031', category: 'focus', isPro: true, path: 'focus/dust-on-the-morning-keys.mp3' },
  { id: 'focus-032', category: 'focus', isPro: true, path: 'focus/glow-on-the-overpass.mp3' },
  { id: 'focus-033', category: 'focus', isPro: true, path: 'focus/porchlight-golden-hour.mp3' },
  { id: 'focus-034', category: 'focus', isPro: true, path: 'focus/sidewalk-slow-jam.mp3' },
  { id: 'focus-035', category: 'focus', isPro: true, path: 'focus/soft-gold-sky.mp3' },
  { id: 'focus-037', category: 'focus', isPro: true, path: 'focus/window-seat-daydream.mp3' },
  { id: 'focus-038', category: 'focus', isPro: true, path: 'focus/ashes-in-the-coffee-cup.mp3' },
  { id: 'focus-039', category: 'focus', isPro: true, path: 'focus/breezy-afternoon-terrace.mp3' },
  { id: 'focus-040', category: 'focus', isPro: true, path: 'focus/candlelit-at-70-bpm.mp3' },
  { id: 'focus-041', category: 'focus', isPro: true, path: 'focus/dust-and-hardcovers.mp3' },
  { id: 'focus-042', category: 'focus', isPro: true, path: 'focus/harbor-before-words.mp3' },
  { id: 'focus-043', category: 'focus', isPro: true, path: 'focus/last-call-in-c-minor.mp3' },
  { id: 'focus-044', category: 'focus', isPro: true, path: 'focus/linen-and-limoncello.mp3' },
  { id: 'focus-046', category: 'focus', isPro: true, path: 'focus/rain-on-the-boulevard.mp3' },
  { id: 'focus-047', category: 'focus', isPro: true, path: 'focus/saxophone-in-the-rain.mp3' },
  { id: 'focus-048', category: 'focus', isPro: true, path: 'focus/stacks-of-quiet-books.mp3' },
  { id: 'focus-049', category: 'focus', isPro: true, path: 'focus/velvet-cigarette-haze.mp3' },

  // ─── NATURE — Free ─────────────────────────────────────────────────────
  { id: 'nature-001', category: 'nature', isPro: false, path: 'nature/petals-after-rain.mp3' },
  { id: 'nature-002', category: 'nature', isPro: false, path: 'nature/fireplace-loop.mp3' },
  { id: 'nature-003', category: 'nature', isPro: false, path: 'nature/mist-over-green-fields.mp3' },
  { id: 'nature-004', category: 'nature', isPro: false, path: 'nature/a-taste-of-spring.mp3' },
  { id: 'nature-005', category: 'nature', isPro: false, path: 'nature/after-school-rain.mp3' },
  { id: 'nature-026', category: 'nature', isPro: false, path: 'nature/tide-stained-polaroids.mp3' },
  { id: 'nature-031', category: 'nature', isPro: false, path: 'nature/misty-steam-quiet-dreams.mp3' },

  // ─── NATURE — Pro ──────────────────────────────────────────────────────
  { id: 'nature-006', category: 'nature', isPro: true, path: 'nature/amber-sidewalks.mp3' },
  { id: 'nature-007', category: 'nature', isPro: true, path: 'nature/amber-windowpane.mp3' },
  { id: 'nature-008', category: 'nature', isPro: true, path: 'nature/autumn-on-the-window-glass.mp3' },
  { id: 'nature-009', category: 'nature', isPro: true, path: 'nature/bloom-between-showers.mp3' },
  { id: 'nature-010', category: 'nature', isPro: true, path: 'nature/blossoms-on-the-pavement.mp3' },
  { id: 'nature-011', category: 'nature', isPro: true, path: 'nature/embers-after-midnight.mp3' },
  { id: 'nature-012', category: 'nature', isPro: true, path: 'nature/fallen-leaves-loop.mp3' },
  { id: 'nature-013', category: 'nature', isPro: true, path: 'nature/fieldnotes-at-dawn.mp3' },
  { id: 'nature-014', category: 'nature', isPro: true, path: 'nature/hammock-in-the-shade.mp3' },
  { id: 'nature-015', category: 'nature', isPro: true, path: 'nature/lemonade-film-grain.mp3' },
  { id: 'nature-016', category: 'nature', isPro: true, path: 'nature/moon-over-red-dunes.mp3' },
  { id: 'nature-017', category: 'nature', isPro: true, path: 'nature/palm-breeze-nap.mp3' },
  { id: 'nature-018', category: 'nature', isPro: true, path: 'nature/petals-in-the-breeze.mp3' },
  { id: 'nature-019', category: 'nature', isPro: true, path: 'nature/picnic-polaroids.mp3' },
  { id: 'nature-020', category: 'nature', isPro: true, path: 'nature/sidewalk-puddles.mp3' },
  { id: 'nature-021', category: 'nature', isPro: true, path: 'nature/snow-on-the-needle.mp3' },
  { id: 'nature-022', category: 'nature', isPro: true, path: 'nature/spring-garden-loops.mp3' },
  { id: 'nature-023', category: 'nature', isPro: true, path: 'nature/starlight-in-the-sand.mp3' },
  { id: 'nature-024', category: 'nature', isPro: true, path: 'nature/storm-over-side-streets.mp3' },
  { id: 'nature-025', category: 'nature', isPro: true, path: 'nature/thunder-in-the-dust.mp3' },
  { id: 'nature-027', category: 'nature', isPro: true, path: 'nature/winter-turntable.mp3' },
  { id: 'nature-028', category: 'nature', isPro: true, path: 'nature/bamboo-shadow-waltz.mp3' },
  { id: 'nature-029', category: 'nature', isPro: true, path: 'nature/bells-before-sunrise.mp3' },
  { id: 'nature-030', category: 'nature', isPro: true, path: 'nature/lanterns-in-slow-motion.mp3' },
  { id: 'nature-032', category: 'nature', isPro: true, path: 'nature/moon-through-bamboo.mp3' },
  { id: 'nature-033', category: 'nature', isPro: true, path: 'nature/paper-lantern-rain.mp3' },
  { id: 'nature-034', category: 'nature', isPro: true, path: 'nature/teacup-morning-fog.mp3' },
  { id: 'nature-035', category: 'nature', isPro: true, path: 'nature/temple-at-dawn.mp3' },

  // ─── AMBIENT — Free ────────────────────────────────────────────────────
  { id: 'ambient-001', category: 'ambient', isPro: false, path: 'ambient/drifting-through-fog.mp3' },
  { id: 'ambient-002', category: 'ambient', isPro: false, path: 'ambient/moonlit-moss.mp3' },
  { id: 'ambient-003', category: 'ambient', isPro: false, path: 'ambient/misty-mountain-sunrise.mp3' },
  { id: 'ambient-021', category: 'ambient', isPro: false, path: 'ambient/warm-constellations.mp3' },
  { id: 'ambient-020', category: 'ambient', isPro: false, path: 'ambient/underwater-dreamscape.mp3' },
  { id: 'ambient-010', category: 'ambient', isPro: false, path: 'ambient/ghosts-on-the-hillside.mp3' },
  { id: 'ambient-022', category: 'ambient', isPro: false, path: 'ambient/cafe-da-tarde.mp3' },

  // ─── AMBIENT — Pro ─────────────────────────────────────────────────────
  { id: 'ambient-004', category: 'ambient', isPro: true, path: 'ambient/almost-floating.mp3' },
  { id: 'ambient-005', category: 'ambient', isPro: true, path: 'ambient/aurora-on-mute.mp3' },
  { id: 'ambient-006', category: 'ambient', isPro: true, path: 'ambient/blue-below-the-surface.mp3' },
  { id: 'ambient-007', category: 'ambient', isPro: true, path: 'ambient/cathedral-hiss.mp3' },
  { id: 'ambient-008', category: 'ambient', isPro: true, path: 'ambient/deep-space-loop.mp3' },
  { id: 'ambient-009', category: 'ambient', isPro: true, path: 'ambient/first-light-on-the-ridge.mp3' },
  { id: 'ambient-011', category: 'ambient', isPro: true, path: 'ambient/glasshouse-ghosts.mp3' },
  { id: 'ambient-012', category: 'ambient', isPro: true, path: 'ambient/green-after-midnight.mp3' },
  { id: 'ambient-013', category: 'ambient', isPro: true, path: 'ambient/orbiting-in-silence.mp3' },
  { id: 'ambient-014', category: 'ambient', isPro: true, path: 'ambient/polar-afterglow.mp3' },
  { id: 'ambient-015', category: 'ambient', isPro: true, path: 'ambient/satellite-lullaby.mp3' },
  { id: 'ambient-016', category: 'ambient', isPro: true, path: 'ambient/sea-glass-evening.mp3' },
  { id: 'ambient-017', category: 'ambient', isPro: true, path: 'ambient/soft-weightless-hours.mp3' },
  { id: 'ambient-018', category: 'ambient', isPro: true, path: 'ambient/stained-glass-static.mp3' },
  { id: 'ambient-019', category: 'ambient', isPro: true, path: 'ambient/tide-pools-at-twilight.mp3' },
  { id: 'ambient-023', category: 'ambient', isPro: true, path: 'ambient/cassette-pastel-nights.mp3' },
  { id: 'ambient-024', category: 'ambient', isPro: true, path: 'ambient/dusk-on-red-earth.mp3' },
  { id: 'ambient-025', category: 'ambient', isPro: true, path: 'ambient/end-scene-glow.mp3' },
  { id: 'ambient-026', category: 'ambient', isPro: true, path: 'ambient/midnight-steam-and-mango-skin.mp3' },
  { id: 'ambient-027', category: 'ambient', isPro: true, path: 'ambient/quiet-credits.mp3' },
  { id: 'ambient-028', category: 'ambient', isPro: true, path: 'ambient/savanna-slow-glow.mp3' },
  { id: 'ambient-029', category: 'ambient', isPro: true, path: 'ambient/vhs-heartbeat.mp3' },
]